#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["dotnet-backend/src/Services/Social/Social.API/Social.API.csproj", "dotnet-backend/src/Services/Social/Social.API/"]
COPY ["dotnet-backend/src/Services/Social/Social.Application/Social.Application.csproj", "dotnet-backend/src/Services/Social/Social.Application/"]
COPY ["dotnet-backend/src/Services/Social/Social.Domain/Social.Domain.csproj", "dotnet-backend/src/Services/Social/Social.Domain/"]
COPY ["dotnet-backend/src/BuildingBlocks/Eventbus.Messages/Eventbus.Messages.csproj", "dotnet-backend/src/BuildingBlocks/Eventbus.Messages/"]
COPY ["dotnet-backend/src/Services/Social/Social.Infrastructure/Social.Infrastructure.csproj", "dotnet-backend/src/Services/Social/Social.Infrastructure/"]
RUN dotnet restore "dotnet-backend/src/Services/Social/Social.API/Social.API.csproj"
COPY . .
WORKDIR "/src/dotnet-backend/src/Services/Social/Social.API"
RUN dotnet build "Social.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Social.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Social.API.dll"]