version: 2.1

# orbs:
#   windows: circleci/windows@2.2.0
#   docker: circleci/docker@1.5.0

executors:
  dind-executor:
    docker:
      - image: 'docker:stable-dind'
    resource_class: small
  scanner:
    docker:
      - image: openjdk:11

parameters:
  run-kweet-workflow:
    type: boolean
    default: false
  run-usertimeline-workflow:
    type: boolean
    default: false
  run-common-workflow:
    type: boolean
    default: false

jobs:
  test-kweetapi:
    description: Test the Kweet API
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            cd dotnet-backend/src/Tests/Unit/Kweet.Application.UnitTests
            dotnet test

  analyse-kweetapi:
    description: Scan with SonarQube
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Install Sonarqube scanner
          command: |
            mkdir -p /usr/share/man/man1 && apt-get update && apt-get install -y --no-install-recommends openjdk-11-jre-headless && rm -rf /var/lib/apt/lists/*
            export JAVA_VER=11
            export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
            export PATH="${PATH}:/root/.dotnet/tools"
            cd dotnet-backend/src/Services/Kweet/Kweet.API
            dotnet tool install dotnet-sonarscanner
            dotnet tool install --global coverlet.console
            dotnet sonarscanner begin /k:"Kwetter" /d:sonar.host.url="http://185.182.185.197:9000" /d:sonar.login=$SONARQUBE_LOGIN /d:sonar.cs.opencover.reportsPaths=coverage.xml
            dotnet build Kweet.API.csproj --no-incremental
            coverlet ./../../../Tests/Unit/Kweet.Application.UnitTests/bin/Debug/net6.0/Kweet.Application.UnitTests.dll --target "dotnet" --targetargs "test --no-build" -f=opencover -o="coverage.xml"
            dotnet sonarscanner end /d:sonar.login=$SONARQUBE_LOGIN

  build-kweetapi:
    description: Build application with Release configuration
    executor: dind-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build and push Docker image"
          command: |
            cd dotnet-backend/src
            docker build -t raycoh/kweet-api -f Dockerfile.kweet .
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
            docker push raycoh/kweet-api

workflows:
  kweetapi:
    when: << pipeline.parameters.run-kweet-workflow >>
    jobs:
      - test-kweetapi
      - analyse-kweetapi:
          requires:
            - test-kweetapi
      - build-kweetapi:
          requires:
            - test-kweetapi
            - analyse-kweetapi
          filters:
            branches:
              only: main
  # usertimeline:
  #   when: << pipeline.parameters.run-usertimeline-workflow >>
  #   jobs:
  #     - build-timelineapi
  #     - build-timelineapi:
  #         filters:
  #           branches:
  #             only: main
  # common:
  #   when: << pipeline.parameters.run-common-workflow >>
  #   jobs:
  #     - build-common
  #     - build-common:
  #         filters:
  #           branches:
  #             only: main