version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  docker: circleci/docker@1.5.0

parameters:
  run-kweet-workflow:
    type: boolean
    default: false
  run-usertimeline-workflow:
    type: boolean
    default: false
  run-common-workflow:
    type: boolean
    default: false

jobs:
  test-kweetapi:
    description: Test the Kweet API
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            cd dotnet-backend/src/Tests/Unit/Kweet.Application.UnitTests
            dotnet test
            ls
      
  build-kweetapi:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build and push Docker image"
          command: ls

workflows:
  kweetapi:
    when: << pipeline.parameters.run-kweet-workflow >>
    jobs:
      - test-kweetapi
      - build-kweetapi:
          requires:
            - test-kweetapi
          filters:
            branches:
              only: main
  # usertimeline:
  #   when: << pipeline.parameters.run-usertimeline-workflow >>
  #   jobs:
  #     - build-timelineapi
  #     - build-timelineapi:
  #         filters:
  #           branches:
  #             only: main
  # common:
  #   when: << pipeline.parameters.run-common-workflow >>
  #   jobs:
  #     - build-common
  #     - build-common:
  #         filters:
  #           branches:
  #             only: main