version: 2.1

# orbs:
#   windows: circleci/windows@2.2.0
#   docker: circleci/docker@1.5.0

executors:
  dind-executor:
    docker:
      - image: 'docker:stable-dind'
    resource_class: small
  scanner:
    docker:
      - image: openjdk:11

parameters:
  run-kweet-workflow:
    type: boolean
    default: false
  run-usertimeline-workflow:
    type: boolean
    default: false
  run-common-workflow:
    type: boolean
    default: false

jobs:
  test-kweetapi:
    description: Test the Kweet API
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Unit tests
          command: |
            cd dotnet-backend/src/Tests/Unit/Kweet.Application.UnitTests
            dotnet test

  analyse-kweetapi:
    description: Scan with SonarQube
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - checkout
      - run:
          name: Install Sonarqube scanner
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-11-jdk && sudo apt-get install -y ant && sudo apt-get clean;
            sudo apt-get update && sudo apt-get install -y ca-certificates-java && sudo apt-get clean && update-ca-certificates -f;
            cd dotnet-backend/src/Services/Kweet/Kweet.API
            dotnet tool install dotnet-sonarscanner
            dotnet sonarscanner begin /k:"Kwetter" /d:sonar.host.url="http://185.182.185.197:9000" /d:sonar.login=$SONARQUBE_LOGIN
            dotnet build Kweet.API.csproj
            dotnet sonarscanner end /d:sonar.login=$SONARQUBE_LOGIN
      
  build-kweetapi:
    description: Build application with Release configuration
    executor: dind-executor
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: "Build and push Docker image"
          command: |
            cd dotnet-backend/src
            docker build -t raycoh/kweet-api -f Dockerfile.kweet .
      - run:
          name: Push to Docker Hub
          command: |
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_ACCESS_TOKEN
            docker push raycoh/kweet-api

workflows:
  kweetapi:
    when: << pipeline.parameters.run-kweet-workflow >>
    jobs:
      - test-kweetapi
      - analyse-kweetapi:
          requires:
            - test-kweetapi
      - build-kweetapi:
          requires:
            - test-kweetapi
            - analyse-kweetapi
          filters:
            branches:
              only: main
  # usertimeline:
  #   when: << pipeline.parameters.run-usertimeline-workflow >>
  #   jobs:
  #     - build-timelineapi
  #     - build-timelineapi:
  #         filters:
  #           branches:
  #             only: main
  # common:
  #   when: << pipeline.parameters.run-common-workflow >>
  #   jobs:
  #     - build-common
  #     - build-common:
  #         filters:
  #           branches:
  #             only: main