apiVersion: v1
kind: Pod
metadata:
  name: kweetapi
spec:
  containers:
  - name: kweetapi
    image: raycoh/kweet-api:latest
    ports:
    - containerPort: 80
    env:
    - name: "ASPNETCORE_ENVIRONMENT"
      value: "Staging"
    - name: "ConnectionStrings__KweetDbConnectionString"
      value: <DATABASE>
    - name: "EventBusSettings__HostAddress"
      value: <CLOUDMQ>