version: '3.4'


services:
  api.kweet:
    container_name: api.kweet
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:KweetDbConnectionString=server=db.kweet;database=KweetDb;user=development;password=development"
      - "EventBusSettings:HostAddress=amqp://guest:guest@service.rabbitmq:5672"
      - "Keycloak:auth-server-url=http://172.22.192.1:8080/auth/"

    depends_on:
        - db.kweet
        - service.rabbitmq
    ports:
        - "8000:80"

  api.usertimeline:
    container_name: api.usertimeline
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=cache.usertimeline:6379"
      - "DatabaseSettings:ConnectionString=mongodb://db.usertimeline:27017"
      - "EventBusSettings:HostAddress=amqp://guest:guest@service.rabbitmq:5672"
    depends_on:
      - db.usertimeline
      - service.rabbitmq
    ports:
      - "8001:80"

  api.social:
    container_name: api.social
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "neo4j:server=bolt://db.neo4j:7687"
      - "neo4j:username=neo4j"
      - "neo4j:password=develop"
    ports:
      - "8002:80"

  db.kweet:
    container_name: db.kweet
    environment:
        MYSQL_ROOT_PASSWORD: "development"
        MYSQL_USER: "development"
        MYSQL_PASSWORD: "development"
        MYSQL_DATABASE: "KweetDb"
    restart: always
    ports:
        - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  db.neo4j:
    container_name: "db.neo4j"
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes: 
      - neo4j_data:$HOME/neo4j/data

  cache.usertimeline:
    container_name: "cache.usertimeline"
    restart: always
    ports:
      - "6379:6379"

  db.usertimeline:
    container_name: db.usertimeline
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  service.rabbitmq:
    container_name: "service.rabbitmq"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"


  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"

