version: '3.4'

services:
  db.kweet:
    image: mysql

  db.usertimeline:
    image: mongo

  cache.usertimeline:
    image: redis:alpine

  db.auth:
    image: postgres:13.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - keycloak

  keycloak:
    depends_on:
      - db.auth
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: db.auth
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    image: jboss/keycloak:latest
    ports:
      - "28080:8080"
    restart: unless-stopped
    networks:
      - keycloak

  service.rabbitmq:
    image: rabbitmq:3-management-alpine

  db.neo4j:
    image: neo4j

  api.kweet:
    image: ${DOCKER_REGISTRY-}kweetapi
    build:
      context: .
      dockerfile: src/Services/Kweet/Kweet.API/Dockerfile

  api.usertimeline:
    image: ${DOCKER_REGISTRY-}usertimelineapi
    build:
      context: .
      dockerfile: src/Services/UserTimeline/UserTimeline.API/Dockerfile

  api.social:
    image: ${DOCKER_REGISTRY-}socialapi
    build:
      context: .
      dockerfile: src/Services/Social/Social.API/Dockerfile

volumes:
  mysql_data:
  mongo_data:
  neo4j_data:

networks:
  keycloak:
